export const CHANGE_ROUTE = 'CHANGE_ROUTE'
export const LOAD_COORDINATES_START = 'LOAD_COORDINATES_START'
export const LOAD_COORDINATES_SUCCESS = 'LOAD_COORDINATES_SUCCESS'
export const LOAD_COORDINATES_ERROR = 'LOAD_COORDINATES_ERROR'
